version: "3.4"
services:
  nodejs:
    image: hluu5/stockx
    container_name: stockx
    build: .
    environment:
      #configure password and host. Password has to match postgres container env password
      - PASSWORD=postgres
      #postgres host is the ip address of your container or your VM. PLEASE CHANGE THIS.
      #DO NOT PREPEND 'http://' before you ip address
      - POSTGRES_HOST=192.168.99.100
      #HOST is the ip address of your container or your VM. PLEASE CHANGE THIS.
      #MAKE SURE TO PREPEND 'http://' before you ip address
      - HOST=http://192.168.99.100
      - SERVER_USER=admin
      - SERVER_PASSWORD=admin
    volumes:
      - .:/etc/src/app
    ports:
      - 4000:4000
    #restart the app if it failed
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      #setup initial postgres username,password and db
      #username and password can be anything you want, but make sure to change the env variables
      #in postgresDB/index.js @line 14 and 16
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stockx
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    restart: always



